---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: omada-controller
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/theautomation/omada-controller.git
    targetRevision: HEAD
    path: deploy/kubernetes
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: networking
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
